### PR TITLE
Feature/add appveyor

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 AppVeyor builds are passing but the rest are failing? Can you have a look?

**Comment by CAMOBAP795** [comment]
@ronaldtse please don't merge it yet, looks like `ubuntu-install-puppeteer.sh` cannot install puppeteer for some reason, I will need to investigate why diff bellow failed on travis

```
-  - npm install -g puppeteer
-  - npm install
-  - unset _JAVA_OPTIONS
+  - travis_retry sudo apt-get update
+  - sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu-install-puppeteer.sh | bash"
```

**Comment by CAMOBAP795** [comment]
Run `https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu-install-puppeteer.sh` without sudo helped

@ronaldtse I have proposal for https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu-install-puppeteer.sh don't try install `node` if `npm` exists

How do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 Agree -- but we need to ensure when Metanorma runs, it *can* find that `npm`.

**Comment by CAMOBAP795** [comment]
@ronaldtse sure, once CI passed it will be ready for merge

**Pull request merged**
